### ISSUE TITLE
osa02-04_taysi_ikaisyys / Pysyvästi kaatunut tehtävä

### ISSUE THREAD

**Issue by kasperworks** [rage/python-kesa20#14]
Otsikon mukainen tehtävä on minulta pysyvästi näkymättömissä. Tehtävä kaatui lähetysvaiheessa ja näkyy TMC:ssä virhestatuksella, nyt tehtävän sijasta minulla on näkyvissä vain seuraava viesti:

Ohjelman osa kaatui:
TypeError: G[0] is undefined

Tämä ongelma toistuu ladatessani sivun uudestaan uusimmalla Firefoxilla, myös ulos- ja uudelleenkirjautuessa. Chromella erikseen kokeiltuna vain virheilmoitus muuttuu, mutta tehtävä pysyy yhä näkymättömissä:

Ohjelman osa kaatui:
TypeError: Cannot read property 'shortName' of undefined

**Comment by jolampi** [comment]
Hei,

Pahoittelemme ongelmaa ja pyrimme nopeasti ratkaisemaan tilanteen. Luultavasti lähetetty tehtävä on sisällöltään jotenkin vioittunut, eikä sitä siksi saadakaan ladattua takaisin editoriin. Tehtävän kaatuminen lähettäessä puolestaan vaikuttaa eri ongelmalta, mutta on luultavasti aiheuttanut tämän toisen.

**Comment by jolampi** [comment]
Paransin äskettäin virheentarkistusta tehtävien lataamisen osalta. Kertoisitko, että palautuiko tehtävä näillä muutoksilla takaisin toimintaan?

**Comment by kasperworks** [comment]
Moi, kiitos nopeasta vastauksesta! Sama ongelma yhä, valitettavasti. Tehtävä yrittää ladata itsensä ja tehtävänanto tuleekin näkyville, mutta kaatuu alle sekunnin päästä, aina siinä vaiheessa kun koodikenttä on tulossa näkyviin.

**Comment by jolampi** [comment]
Harmin paikka. Voisitko antaa linkin kyseiseen tehtävän palautukseen https://tmc.mooc.fi -sivustolla, niin pyrimme selvittämään tarkemmin, että mistä on kysymys?

Toimiihan muut tehtävät normaallisti?

**Comment by kasperworks** [comment]
Jep, kaikki muut tehtävät toimivat aivan mainiosti. Tämä virhe sattui pätkivän yhteyden kanssa eilen, luultavasti yhteys katkesi kesken lähetyksen ja kenties jokin puolittainen paketti tukkii nyt tien?

Tehtävä on tässä: https://tmc.mooc.fi/exercises/93652
Logissa näkyy kaksi "Error"-viestiin päättynyttä lähetystä, ensimmäinen 08.06.2020 15:01 ja toinen 08.06.2020 15:02. 

Detaljeja klikatessa näen vain seuraavan viestin: "We're sorry, but something went wrong. Please ask an administrator to look at the server logs."

**Comment by jolampi** [comment]
Hyvä, että ainakin muut tehtävät toimivat. Jatkamme ongelman selvittämistä. Voit yrittää tähän hätään ladata tuolta sivulta tehtäväpohja-zipin ja palauttaa sen semmoisenaan last resort -kohtaan, jos tämä mahdollistaisi taas tehtävän suorittamisen.

**Comment by kasperworks** [comment]
Kiitos, tehtäväpohja-zipin palautus sellaisenaan ratkaisi ongelman minun osaltani ja tehtävän suoritus onnistui!
