### ISSUE TITLE
Osa 3 tehtävä Monta tulostusta 

### ISSUE THREAD

**Issue by emaali** [rage/python-kesa20#23]
Kyseisessä tehtävässä pyydetään määrittelemään funktio "tulosta_monesti(merkkijono, kertaa). 
Tehtävän tarkistuksessa käytetään kuitenkin funktiota: "monta_tulostusta("testi", 2)", mikä johtaa seuraavaan virheeseen:

Funktiokutsun monta_tulostusta("testi", 2) jokaisen tulostusrivin pitäisi olla testi, seuraava rivi tulostuu väärin:
2
funktion koko tulostus oli:
2
2

**Comment by mluukkai** [comment]
pitäisi nähdä koodi jotta tästä voisi sanoa mitään

**Comment by emaali** [comment]
def tulosta_monesti(merkkijono, kertaa):
    merkkijono = input("Merkkijono: ")
    kertaa = int(input("Tulostuksia: "))
    x = 0
    while x < kertaa:
        print(merkkijono)
        x += 1





# tee ratkaisu tähän
# funktiota kannattaa testata kutsumalla sitä täällä seuraavasti
tulosta_monesti("testi", 2)
#monta_tulostusta("testi", 2)

ti 30. kesäk. 2020 klo 21.37 Matti Luukkainen (notifications@github.com)
kirjoitti:

**Comment by mluukkai** [comment]
ongelma ovat nuo kaksi enimmäistä riviä, ne eivät kuulu funktioon ollenkaan ja sekottavat testit. testin virheilmotus on kyllä huono

**Comment by mluukkai** [comment]
paransin virheilmotusta siten, että se varottaa syötteen lukemisesta
