### ISSUE TITLE
Osan 4 tehtävässä Positiivisten summa tarkistuksessa on virhe

### ISSUE THREAD

**Issue by mcturkki** [rage/python-kesa20#25]
# tee ratkaisu tänne
list=[]
summa=[]

def positiivisten_summa(list):
    for i in list:
        if i>0:
            summa.append(i)
    
    return sum(summa)
lista = [1, -1, 2, -2, 3, -3]
vastaus = positiivisten_summa(lista)
print("vastaus", vastaus)

Kyseisellä koodilla TMC väittää että ohjelmani tulostaa positiivisten lukujen summaksi 12 vaikka ohjelman ajamalla vastaukseksi tulee 6. Tämän takia en saa tehtävää läpi.

**Comment by mluukkai** [comment]
koodi käyttää glbaaleja muuttujia joten se ei toimi kunnolla. kokeile mitä käy kun teet 

```
lista = [1, -1, 2, -2, 3, -3]
vastaus = positiivisten_summa(lista)
print("vastaus", vastaus) 
vastaus = positiivisten_summa(lista)
print("vastaus", vastaus) 
```

ts funktion pitää toimia riippumatta kuinka monta kertaa sitä kutsutaan
