### ISSUE TITLE
Osa 2:reseptien hakeminen valmistusaika perusteella    kirjoitusvirhe   20 min !!!

### ISSUE THREAD

**Issue by tinygren** [rage/python-kesa20#31]
Osa 2:reseptien hakeminen valmistusaika perusteella

loydetyt = hae_aika("reseptit1.txt", 20)

for resepti in loydetyt:
    print(resepti)
Esimerkkitulostus
Lettutaikina, valmistusaika 15 min

kommentti:   hae aika -funktio saa parametriksi aika = 20 ...mutta tulostuksessa ...tulee 15 min .

**Comment by mluukkai** [comment]
Tehtävässä haetaan ne reseptit joiden valmistusaika on KORKEINTAAN
parametrina oleva luku

pe 10.7.2020 klo 17.41 TIMO TUOMAS NYGREN <notifications@github.com>
kirjoitti:

**Comment by tinygren** [comment]
Oi kiitos nopasta vastauksesta...!!!

t. timo
ps. olimpa huolimaton...
